version: "3.1"

services:
  mongo:
    image: mongo:4.4-bionic
    # restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
      - 28017:28017
    networks:
      infranet:
        aliases:
          - "mongo"

networks:
  infranet:

volumes:
  mongo_data:
